### ISSUE TITLE
found a glitch when using _ on profile

### ISSUE THREAD

**Issue by rslgp** [thejaviertc/javiertcs-api#246]
this users adds this char on their steam profile: '_'
that makes the search get bugged
https://steamcommunity.com/id/Chuckleberry_Finn/

to solve this, i go after his steam profile id number here
https://www.steamidfinder.com/lookup/Chuckleberry_Finn/

then by placing using number it worked https://steamcommunity.com/profiles/76561198012326036

**Comment by thejaviertc** [comment]
Problem found. It was the regexp group that was ignoring "_" so was getting "Chuckleberry" instead of "Chuckleberry_Finn"

Fixed in [3531ad5](https://github.com/thejaviertc/javiertcs-api/commit/3531ad569cae2ae0c0666789cd8a7c0d740a234a), will be available on v1.2.0 release soon
